development:
  adapter: postgresql
  encoding: unicode
  database: support_hero_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: support_hero_test
  pool: 5
  username:
  password: